### PR TITLE
Added freeze/unfreeze option for sources

### PR DESCRIPTION
**Pull request by JeffreyDavidsz**
use source ID and type of source
not tested yet

### CODE REVIEW

**Comment by willosof** [comment]
You need to fix your indentation. Have you tested the features? :)

**Comment by JeffreyDavidsz** [comment]
Hi William, I'm not able to test :-( just typing and hope for the best....

**Comment by JeffreyDavidsz** [comment]
Thing is I'm completely new here and a starter in programming, I'll try to build from visual studio and see if this works

**Comment by willosof** [comment]
This is not a compiling application, so visual studio won't do you any good. 
Check out https://github.com/bitfocus/companion/blob/master/DEVELOPER.md

**Comment by JeffreyDavidsz** [comment]
I've tried the explanation, seems windows 10 is missing some support? Little above my paygrade. Getting errors about ". " when using npm run start. I have a friend who might know more and can help me, sorry

**Comment by haakonnessjoen** [comment]
While you wait for your friend, you should change your indentation from spaces to tabs and commit the fix :)

**Comment by JeffreyDavidsz** [comment]
Tnx I will do that, and rebase first, hold on :-)

**Comment by JeffreyDavidsz** [comment]
Sould be ok now right?

**Pull request merged**
